version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=academic_helper
      - POSTGRES_USER=student
      - POSTGRES_PASSWORD=secure_password
      - JWT_SECRET_KEY=your_jwt_secret_here
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - N8N_WEBHOOK_URL=http://n8n:5678/webhook/assignment
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - academic-network

  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=false
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=academic_helper
      - DB_POSTGRESDB_USER=student
      - DB_POSTGRESDB_PASSWORD=secure_password
    depends_on:
      - postgres
    volumes:
      - n8n_data:/home/node/.n8n
      - ./n8n-workflows:/data
    networks:
      - academic-network

  postgres:
    image: pgvector/pgvector:pg16
    environment:
      - POSTGRES_DB=academic_helper
      - POSTGRES_USER=student
      - POSTGRES_PASSWORD=secure_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - academic-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@academic.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - academic-network

volumes:
  postgres_data:
  n8n_data:

networks:
  academic-network:
    driver: bridge